### PR TITLE
fix: warn if transparent background is set after opaque init

### LINKED ISSUE #10162: Bug: Transparent Background doesn't work
### Current Behavior

The background transparency is not set further if I initialize the application with an opaque background.

### Expected Behavior

The background transparency should be set further if I initialize the application with an opaque background.

### Steps to Reproduce

1. Open example here [https://pixijs.com/examples/basic/transparent-background](https://pixijs.com/examples/basic/transparent-background)
2. Remove backgroundAlpha from constructor options. 
const app = new PIXI.Application({ backgroundColor: 'green', resizeTo: window });
// ... some code
3. Set a new background (red + 0.5 alpha)
app.renderer.background.color = 'rgba(255, 0, 0, 0.5)'; // doesn't work

Note: If backgroundAlpha is set to 0 in constructor then step 3 is works.

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Ashish050488**
##### Description of change
Fixes #10162

This PR adds a developer-facing warning when a transparent background color (like `'rgba(255, 0, 0, 0.5)'`) is set **after** the canvas has been initialized with `backgroundAlpha: 1` (i.e., opaque).

Browsers do not allow changing the canvas alpha setting after initialization. This silent behavior has confused many developers.

✅ This PR includes:
- A `warn()` message wrapped in `#if _DEBUG` so it’s dev-only
- An updated JSDoc comment for `backgroundAlpha` explaining that the alpha must be set at initialization time
- Clean code style consistent with PixiJS standards

This was previously merged into my fork by mistake — resubmitting here for the official PixiJS `dev` branch.

---

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included _(N/A for dev-only warning)_
- [x] Documentation is changed or added (JSDoc for `backgroundAlpha`)
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

File: src/rendering/renderers/shared/background/BackgroundSystem.ts [hunk 1]
```diff
@@ -111,6 +114,18 @@ export class BackgroundSystem implements System<BackgroundSystemOptions>
 
     set color(value: ColorSource)
     {
+        // #if _DEBUG
+
+        const incoming = new Color(value);
```
Comment (Zyie) [inline src/rendering/renderers/shared/background/BackgroundSystem.ts:119]:
```suggestion
        const incoming = Color.shared.setValue(value);
```
