### PR TITLE
Fix docs for graphicsUtils namespace and members

### LINKED ISSUE #6648: PIXI.Star returns an error on using.
### Expected Behavior
The star is drawn.
### Current Behavior
The star is not shown and return this error : Uncaught TypeError: PIXI.Star is not a constructor.
### Possible Solution
Re-implement the PIXI.Star class. 
### Steps to Reproduce
Put new PIXI.Star(0,0,50,25); and it will result an error.
### Environment

- **`pixi.js` version**: _5.2.4_
- **Browser & Version**: _Chrome 81.0.4044.138_
- **OS & Version**: _Windows 10_
- **Running Example**:  https://www.pixiplayground.com/#/edit/FEFF3OlTl28XK0vNIPFBG

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Fixes #6648 - Star polygon class is part of `graphicsUtils` namespace not root.

Also, members of this class documented incorrectly. Fixed the names.

```
exports.BATCH_POOL
exports.DRAW_CALL_POOL
exports.FILL_COMMANDS
```

Current dev (broken)
http://pixijs.download/dev/docs/PIXI.graphicsUtils.html

This PR (fixed)
http://pixijs.download/dev-graphics-docs/docs/PIXI.graphicsUtils.html

### CODE REVIEW

File: packages/graphics/src/utils/index.ts [hunk 1]
```diff
@@ -1,7 +1,8 @@
 /**
  * Generalized convenience utilities for Graphics.
  *
- * @namespace PIXI.graphicsUtils
+ * @namespace graphicsUtils
+ * @memberof PIXI
```
Comment (SukantPal) [inline packages/graphics/src/utils/index.ts:5]: This is a better approach than using `@namespace PIXI.graphicsUtils`!

File: packages/graphics/src/utils/index.ts [hunk 2]
```diff
@@ -47,14 +48,14 @@ export const FILL_COMMANDS: Record<SHAPES, IShapeBuildCommand> = {
  * Batch pool, stores unused batches for preventing allocations.
  *
  * @memberof PIXI.graphicsUtils
- * @type {Array<PIXI.graphicsUtils.BatchPart>}
+ * @member {Array<PIXI.graphicsUtils.BatchPart>} BATCH_POOL
```
Comment (SukantPal) [inline packages/graphics/src/utils/index.ts:51]: I think renaming the documentation here is unnecessary but works :)

Comment (bigtimebuddy) [reply packages/graphics/src/utils/index.ts:51]: JSDoc has issues with ES6 exports 😦 This was a case where it inferred the name as `exports.BATCH_POOL` instead of just `BATCH_POOL`. Having a better doc parser would help or, what I've seen in other places as a good stylistic choice, is don't do `export class`, `export let`, etc as inline, and do your exports at the bottom of the document `export { BATCH_POOL }`. It's easier to see exports all in one place.
