### PR TITLE
Mask/Fill interaction tests + fix

### LINKED ISSUE #3151: Interactivity problem with masked elements (v4.1.0)
Hello, I just updated pixi with the last update (from 4.0.3 to 4.1.0) and I immediately noticed a bug with elements using masks, the interactivity (over, click, even the cursor changing) don't work when a mask is assigned. I use a PIXI.Graphics object as the mask.

### PR DESCRIPTION
**Pull request by staff0rd**
Prior to the fix being added, the test state was this;

✔️ should trigger interaction callback when no mask present
✔️ should trigger interaction callback when mask uses beginFill
✔️ should not trigger interaction callback when mask doesn't use beginFill
❌  should trigger interaction callback when mask doesn't use beginFill but hitArea is defined
❌ should trigger interaction callback when mask doesn't use beginFill but filterArea is defined
✔️ should trigger interaction callback when mask is a sprite

All tests pass after 9658fc6.

Resolves #3151 and the duplicate #3589

### CODE REVIEW

File: src/interaction/InteractionManager.js [hunk 1]
```diff
@@ -788,19 +788,19 @@ export default class InteractionManager extends EventEmitter
...
+            if (!displayObject.filterArea.contains(point.x, point.y))
             {
                 hitTest = false;
             }
         }
 
-        // it has a filterArea! Same as mask but easier, its a rectangle
-        if (hitTest && displayObject.filterArea)
+        // it has a mask! Then lets hit test that before continuing if no hitArea or filterArea is present
+        if (hitTest && displayObject._mask && !displayObject.hitArea && !displayObject.filterArea)
```
Comment (GoodBoyDigital) [inline src/interaction/InteractionManager.js]: do we need this last bit? ```&& !displayObject.hitArea && !displayObject.filterArea``` ?

**Comment by GoodBoyDigital** [comment]
Also what @bigtimebuddy said! Big respect for constantly adding tests and bringing more stability to PIXI :D What would we do without you!

File: src/interaction/InteractionManager.js (hunk 1 above)
Comment (staff0rd) [inline src/interaction/InteractionManager.js]: @GoodBoyDigital actually, that part _is_ the fix.  Without it, [this](https://github.com/pixijs/pixi.js/blob/ccb99cff69889c228e820969cf8e01af699c82e6/src/core/graphics/Graphics.js#L863-L866) code will be hit (for masks not using `beginFill`) and `hitTest` will be set to false, causing the relevant events to not be emitted.

Prior to the fix, a mask overrides all other hitTests.  After the fix, priority is given to the existence of `hitArea` or `filterArea` over the presence of a mask.

Does this make sense?

Comment (GoodBoyDigital) [inline src/interaction/InteractionManager.js]: Ahh that does! Just gonna throw this out there - but wander if we should even test for filter area. The purpose was to optimise filters rather than interaction. 

The majority of the time the filter area is set to something massive too, offering very little in way of optimisation here..

I think we should remove the check.. 

What are your thoughts?

Cheers!

Comment (staff0rd) [inline src/interaction/InteractionManager.js]: @GoodBoyDigital yeah I don't use filters so I can't really comment.  I'll pull it out if you want?

Comment (bigtimebuddy) [inline src/interaction/InteractionManager.js]: I agree with @GoodBoyDigital, `filterArea` is not intended to be used as interaction area. I think we should pull that out.

Comment (staff0rd) [inline src/interaction/InteractionManager.js]: yanked :v:

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital ping. Could you take a look at this again?
