### PR TITLE
fix: Video Loader Not Catching Load Errors

### LINKED ISSUE #11845: Video Loader Not Catching Load Errors
### PixiJS version

8.15.0

### Link to minimal reproduction

https://jsfiddle.net/7o5f2wh3/

### Steps to reproduce

`Assets.load()` does not capture errors in loading videos.

```ts
  await Assets.load("fake_file.webp").catch(e => {
    console.log("FAILED TO LOAD WEBP FILE")
  })

  await Assets.load("fake_file.mp4").catch(e => {
    console.log("FAILED TO LOAD MP4 FILE")
  })
```

### What is expected?

The loader, based on the documentation, should return the same kind of error regardless of the file type that failed to load.

For the example above, the console output should be:
```
FAILED TO LOAD WEBP FILE
FAILED TO LOAD MP4 FILE
```

### What is actually happening?

Currently, it is not possible to catch errors in loading videos.

The output of the code example is this:
```
FAILED TO LOAD WEBP FILE
```

### Environment

- **Browser & Version**: *e.g. Firefox 146.0.1*
- **OS & Version**: *e.g. Ubuntu 25.10*

### Any additional comments?

I assume it's a missing event handler. I can see that the preload functionality wires in the `error` handler, but experimenting with forcing preload leads to the same outcome. It's possible that another event altogether is fired on a 404 or network error.

### PR DESCRIPTION
**Pull request by stargazer-2697**
##### Description of change

Fixes #11845 by adding error event handlers to both the video element and source element. Video error events can fire on the `<source>` element, not just the parent `<video>` element, so both need listeners.

##### Pre-Merge Checklist

Automated tests are difficult due to the reliance on DOM events and callbacks. The jsFiddle in the linked issue was used to validate the fix, although it should be noted that the error message is still logged to `console.error` in Chrome 143.0.7499.193 despite bring handled by `Promise::catch`.

- [ ] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

File: src/assets/loader/parsers/textures/loadVideoTextures.ts [hunk 1]
```diff
@@ -268,12 +268,27 @@ export const loadVideoTextures = {
...
+                cleanup();
+                reject(event);
+            };
+
+            function cleanup(): void
+            {
+                videoElement.removeEventListener('canplay', onCanPlay);
+                videoElement.removeEventListener('error', onError);
+                sourceElement.removeEventListener('error', onError);
+            }
```
Comment (bigtimebuddy) [inline src/assets/loader/parsers/textures/loadVideoTextures.ts]: nit, we prefer fat arrows for inline functions to maintain a single context.

```suggestion
            const cleanup = (): void =>
            {
                videoElement.removeEventListener('canplay', onCanPlay);
                videoElement.removeEventListener('error', onError);
                sourceElement.removeEventListener('error', onError);
            };
```

**Review by bigtimebuddy — APPROVED** [review]
Thank you!

File: src/assets/loader/parsers/textures/loadVideoTextures.ts (hunk 1 above)
Comment (stargazer-2697) [reply src/assets/loader/parsers/textures/loadVideoTextures.ts]: @bigtimebuddy Avoiding the lint error after switching to arrow functions is difficult due to the circular dependencies between the closures. I've updated the code to use a function hoisting style, which is consistent with `preloadVideo` above. Is that acceptable?

https://github.com/pixijs/pixijs/blob/ab7dae3108fb0728e53f3d4828134d867a4eb820/src/assets/loader/parsers/textures/loadVideoTextures.ts#L47-L74
