### PR TITLE
fix: copy modifier keys from TouchEvent to normalized touch objects

### LINKED ISSUE #11879: CtrlKey, ShiftKey properties are always false in FederatedEvent
### PixiJS version

8.16

### Link to minimal reproduction

https://www.pixiplayground.com/#/edit/EYXfodAfPmzfj8h6gFGUs

### Steps to reproduce

- Create a Sprite and register an event down handler (say console.log)
- Check the console.log() for the event.ctrlKey property.

### What is expected?

Properties ctrlKey and shiftKey are set according to the originalEvent. Button and buttons propertie are set correctly.

### What is actually happening?

Above properties are always false regardless of key presses. In addition, the button and buttons properties are not working ( always set to -1 and 0 ).

### System Info

```Shell
System:
    OS: Linux 6.18 Fedora Linux 43 (KDE Plasma Desktop Edition)
    Container: Yes
    Shell: 5.3.0 - /bin/bash
  Browsers:
    Chrome: 144.0.7559.109
```

### Any additional comments?

There was an issue here but it seems we have a regression:
https://github.com/pixijs/pixijs/issues/9241

### PR DESCRIPTION
**Pull request by kaigritun**
## Summary

Fixes #11879 - `ctrlKey`, `shiftKey`, `altKey`, and `metaKey` properties are always `false` in FederatedEvent for touch events.

## Root Cause

When touch events are normalized in `_normalizeToPointerData`, the modifier keys (`ctrlKey`, `shiftKey`, `altKey`, `metaKey`) were not being copied from the `TouchEvent` to the normalized touch objects.

These modifier key properties exist on the `TouchEvent` interface, not on individual `Touch` objects. When `_transferMouseData` later tried to read these properties from the normalized touch object, they were `undefined`.

## Changes

1. **PixiTouch interface** (`FederatedEvent.ts`): Added `altKey`, `ctrlKey`, `metaKey`, and `shiftKey` properties

2. **_normalizeToPointerData** (`EventSystem.ts`): Copy modifier keys from the parent `TouchEvent` to each normalized touch object

3. **Tests**: Added test to verify modifier keys are preserved in events

## Testing

- All existing tests pass
- Added new test that verifies modifier keys are correctly preserved through the event system

---

##### Fixes
- Copy modifier keys (ctrlKey, shiftKey, altKey, metaKey) from the original TouchEvent to normalized touch objects so FederatedEvent touch events reflect the correct modifier state.
- Add modifier key properties to the PixiTouch interface so normalized touch objects expose these keys.
    ```ts
    interface PixiTouch {
      altKey?: boolean;
      ctrlKey?: boolean;
      metaKey?: boolean;
      shiftKey?: boolean;
      // ...existing properties
    }
    ```
- Ensure modifier keys are preserved end-to-end through the event system; includes a new test verifying modifier key (and button/buttons) preservation.

### CODE REVIEW

File: src/events/EventSystem.ts [hunk 1]
```diff
@@ -997,6 +997,13 @@ export class EventSystem implements System<EventSystemOptions>
                 touch.isNormalized = true;
                 touch.type = event.type;
 
+                // Copy modifier keys from the TouchEvent to the touch object
+                // These properties exist on TouchEvent, not on individual Touch objects
+                if (typeof touch.altKey === 'undefined') touch.altKey = event.altKey;
+                if (typeof touch.ctrlKey === 'undefined') touch.ctrlKey = event.ctrlKey;
+                if (typeof touch.metaKey === 'undefined') touch.metaKey = event.metaKey;
+                if (typeof touch.shiftKey === 'undefined') touch.shiftKey = event.shiftKey;
```
Comment (bigtimebuddy) [inline src/events/EventSystem.ts]: This could be simplified like this:

```suggestion
                touch.altKey ??= event.altKey;
                touch.ctrlKey ??= event.ctrlKey;
                touch.metaKey ??= event.metaKey;
                touch.shiftKey ??= event.shiftKey;
```

**Comment by kaigritun** [comment]
Thanks @bigtimebuddy for the suggestion! Much cleaner with nullish coalescing assignment. Applied in 132dc41.

**Review by bigtimebuddy — APPROVED** [review]
Nice one!

**Comment by sophon-aniketos** [comment]
thanks a lot for the quick fix !. We need this.

**Comment by MichaelDeBoey** [comment]
I'm not making any claims about the quality of their work, but I wanted to let you know that @kaigritun is a fully-autonomous non-human actor
https://socket.dev/blog/ai-agent-lands-prs-in-major-oss-projects-targets-maintainers-via-cold-outreach

**Comment by sophon-aniketos** [comment]
Wow that's truly unexpected. Thanks.
