### PR TITLE
Remove forceFXAA Application and Renderer option

### LINKED ISSUE #6444: Sprite glitch with antialiasing
In some situations a Sprite has a visible corner-to-corner glitch with antialiasing enabled. I was able to reproduce this in the playground by first drawing a full-screen sprite and then another sprite on top of it: https://www.pixiplayground.com/#/edit/Kj8yLiP9bFoPIeMvNzyYe

### Expected Behavior

Drawing a Sprite on top of a previous Sprite should fully cover the old Sprite without any bleeding artifacts.

### Current Behavior

I'm not sure whether the bug is visible with all display resolutions, but it is clearly visible on my QHD display. Here's a 10x zoom of the image where the red Sprite drawn before the white Sprite is bleeding through the polygon edges in the middle: image

### Possible Solution

I'm not sure what is causing this. It could have something to do with all of the Sprites being drawn with the same z-value but I haven't really investigated this any further than the repro-case in the playground.

### Steps to Reproduce

See the linked playground example.

### Environment

- **`pixi.js` version**:  5.2.1
- **Browser & Version**: Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- **OS & Version**:  Windows 10 Pro
- **Running Example**: https://www.pixiplayground.com/#/edit/Kj8yLiP9bFoPIeMvNzyYe
- **Display Card**: Nvidia GTX 1650 (driver 442.19)

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Partially fixes #6444 

We have long discarded the use of `forceFXAA` functionality (last implemented in v3), this removes from docs and typings.

### CODE REVIEW

File: packages/core/src/Renderer.ts [hunk 1]
```diff
@@ -98,8 +98,6 @@ export class Renderer extends AbstractRenderer
      *   resolutions other than 1.
      * @param {boolean} [options.antialias=false] - Sets antialias. If not available natively then FXAA
```
Comment (qtiki) [inline packages/core/src/Renderer.ts]: Missed a spot here: _"If not available natively then FXAA antialiasing is used"_.

Comment (bigtimebuddy) [reply packages/core/src/Renderer.ts]: Yup! Good catch
