### PR TITLE
Fix bitmap font loader to load fonts with random placed args into <info> tag in 5.4.0-rc.2

### LINKED ISSUE #7008: BitmapFonts no longer getting processed by the Loader in 5.4.0-rc.2
My Bitmap Fonts no longer seem to be recognized after being loaded. I can see the .fnt file in Loader.resources, but PIXI.BitmapFont.available returns an empty object. This worked in 5.3.3.

### PR DESCRIPTION
**Pull request by SerG-Y**
##### Description of change

Fix #7008 
- For BitmapFont text format that's XML-based check if <font> tag exist than parse as XML and check if needed tags exist
- Added test for case when args into <info> tag placed randomly

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

File: packages/text-bitmap/src/formats/XMLStringFormat.ts [hunk 1]
```diff
@@ -19,9 +19,14 @@ export class XMLStringFormat
      */
     static test(data: unknown): boolean
     {
-        const xmlStringRegExp = new RegExp(/<font>(\s+)?<info\s+face=/);
+        if (typeof data === 'string' && data.includes('<font>'))
```
Comment (bigtimebuddy) [inline packages/text-bitmap/src/formats/XMLStringFormat.ts:22]: Could you use `indexOf` instead of `includes`, since `includes` [is not ES5](https://caniuse.com/es6-string-includes) and not supported on IE11.

**Review by bigtimebuddy — CHANGES_REQUESTED** [review]
Small change, otherwise looks good @SerG-Y

**Review by bigtimebuddy — APPROVED** [review]
Nice work :+1:

**Review by andrewstart — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks @SerG-Y! Feel free to [submit an expense](https://opencollective.com/pixijs/expenses/new) to Open Collective for $25 for solving this bug.
