### PR TITLE
Fixed webGLVersion of context

### LINKED ISSUE #6847: ContextSystem#initFromOptions fails to extract webGLVersion
```js
const view = document.createElement('canvas');

const renderer = autoDetectRenderer({
  context: view.getContext('webgl2'),
  view
})

console.log(renderer.context.webGLVersion); // = 1
```

This happens because the `ContextSystem#createContext` method sets the `webGLVersion`. That code path is not invoked when passing a custom context.

### PR DESCRIPTION
**Pull request by JetLua**
Fixed #6847 

demo: https://www.pixiplayground.com/#/edit/5HPwteo_LzF8BVrFGRa5i

### CODE REVIEW

File: packages/core/src/context/ContextSystem.ts [hunk 1]
```diff
@@ -285,6 +285,13 @@ export class ContextSystem extends System
     {
         const attributes = gl.getContextAttributes();
 
+        const isWebGl2 = gl instanceof window.WebGL2RenderingContext;
```
Comment (bigtimebuddy) [inline packages/core/src/context/ContextSystem.ts:288]: This will throw an error if `window.WebGL2RenderingContext` is undefined. Which is part of the reason for having the `'WebGL2RenderingContext' in window` check.

**Review by bigtimebuddy — APPROVED** [review]
:+1:

**Review by ivanpopelyshev — APPROVED** [review]

**Review by SukantPal — APPROVED** [review]
LGTM!

**Comment by bigtimebuddy** [comment]
Thank you @JetLua for this fix, good one :+1:
